server:
  port: ${port:8814}
#  use-forward-headers: true
#  tomcat:
#    protocol-header: X-FORWARDED-PROTO
#    remote-ip-header: X-FORWARDED-FOR
#    port-header: X-Forwarded-Port
#    max-threads: 100
spring:
#  aop:
#    auto: true
#    proxy-target-class: true
  application:
    name: SmsGate
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/smsgate?characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true
    username: root
    password: hz123456
    initSize: 20
    minIdle: 20
    maxActive: 100





    # 使用druid数据源
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    filters: stat
#    maxActive: 20
#    initialSize: 1
#    maxWait: 60000
#    minIdle: 1
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select 'x'
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxOpenPreparedStatements: 20

#logging:
#  path: G:/log/
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    host: 127.0.0.1
    port: 6379
    password: mwkjhz2019





#    pool:
#      # 连接池最大连接数（使用负值表示没有限制）
#      max-active: 8
#      # 连接池中的最大空闲连接
#      max-idle: 8
#      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#      max-wait: -1
#      # 连接池中的最小空闲连接
#      min-idle: 0
#      # 连接超时时间（毫秒）
#    timeout: 0



 
 
